version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
      - name: category
      - name: price

  - name: stg_stores
    columns:
      - name: store_id
        tests:
          - unique
          - not_null
      - name: store_name
      - name: location

  - name: stg_deliveries
    columns:
      - name: delivery_id
        tests:
          - unique
          - not_null
      - name: order_id
      - name: store_id
      - name: delivery_date
      - name: delivery_time
